language: node_js

sudo: false

node_js:
  - stable

install:
  - npm install

script:
  - npm test

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

after_success: npm run coveralls
